#!/bin/bash

# Iterate over subfolders
for dir in x1*; do
    # Navigate to the subfolder
    cd "$dir" || { echo "Failed to change directory to $dir"; continue; }
 
    #Generate PDB files
    ~/packmol/packmol < lj.inp
   
    # Load the VMD module
    module load vmd

    # Execute VMD command in batch mode
#    vmd -dispdev text -e ../change_resname_vmd.tcl
    vmd -dispdev text -eofexit -e ../change_resname_vmd.tcl < /dev/null

    # Delete the first 26 lines and replace with header lines
    if [[ "$dir" == "x1=0.0" ]] || [[ "$dir" == "x1=1.0" ]]; then
    	sed -i '1,22d' system.data
    else
        sed -i '1,24d' system.data
    fi

    sed -i '1i\# LAMMPS data file. CGCMM style. atom_style atomic generated by VMD/TopoTools v1.7 on Thu Mar 28 10:45:55 EDT 2024' system.data
    sed -i '2i\16000 atoms' system.data
    sed -i '3i\0 bonds' system.data
    sed -i '4i\0 angles' system.data
    sed -i '5i\0 dihedrals' system.data
    sed -i '6i\0 impropers' system.data
    if [[ "$dir" == "x1=0.00" ]] || [[ "$dir" == "x1=1.0" ]]; then
        sed -i '7i\1 atom types' system.data
    else
        sed -i '7i\2 atom types' system.data
    fi
    sed -i '8i\0 bond types' system.data
    sed -i '9i\0 angle types' system.data
    sed -i '10i\0 dihedral types' system.data
    sed -i '11i\0 improper types' system.data
    if [[ "$dir" == "x1=0.00" ]]; then
  	sed -i '12i\-11.500000 11.500000  xlo xhi' system.data
    	sed -i '13i\-11.500000 11.500000  ylo yhi' system.data
    	sed -i '14i\-40.000000 40.000000  zlo zhi' system.data
    else
        sed -i '12i\-11.500000 11.500000  xlo xhi' system.data
        sed -i '13i\-11.500000 11.500000  ylo yhi' system.data
        sed -i '14i\-40.000000 40.000000  zlo zhi' system.data
    fi
    sed -i '15i\\' system.data
    sed -i '16i\# Pair Coeffs' system.data
    sed -i '17i\#' system.data
    sed -i '18i\# 1  1' system.data
    sed -i '19i\# 2  2' system.data
    sed -i '20i\\' system.data
    # Add Masses based on $dir value
    if [[ "$dir" == "x1=0.00" ]] || [[ "$dir" == "x1=1.0" ]]; then
	sed -i '21i\Masses' system.data
        sed -i '22i\\' system.data
        sed -i '23i\1 1.0 # 2' system.data
    else
        sed -i '21i\Masses' system.data
    	sed -i '22i\\' system.data
    	sed -i '23i\1 1.0 # 1' system.data
    	sed -i '24i\2 1.0 # 2' system.data
    fi
     # Move back to the parent directory
    cd ..
done

